# (1) Khởi tạo mảng
- Đây là bước đầu tiên để làm việc với Numpy, ta dùng ndarray

In [ ]:
import numpy as np
# Tạo mảng từ list hoặc tuple
# Hàm np.array() chỉ chấp nhận MỘT đối tượng dữ liệu đầu vào (một list, hoặc một 
# tuple...) làm tham số đầu tiên.
np.array()
np.array([1, 2, 3])

# Tạo mảng toàn số 0 (thường dùng để khởi tạo trọng số)
np.zeros()
arr = np.zeros((3, 4))

# Tạo mảng toàn số 1 
np.ones()
np.ones((2, 2))

# Tạo mảng với một giá trị cụ thể bất kỳ
np.full()
np.full((2, 3), 7)

# Tạo mảng số nguyên theo bước nhảy (giống Range của Python)
np.arange()
np.arange(0, 10, 2) # [0, 2, 4, 6, 8]

# Tạo mảng chia đều khoảng cách giữa 2 giá trị (rất quan trọng khi vẽ đồ thị)
np.linspace()
np.linspace(0, 1, 5) # 5 điểm từ 0 đến 1

# Tạo ma trận đơn vị
np.eye()
np.eye(3)

# Tạo mảng ngẫu nhiên (phân phối đều 0-1)
np.random.rand()
np.random.rand(3, 2)

# (2) Kiểm tra & Thuộc tính mảng

In [ ]:
# Kích thước của mảng
arr.shape

# Tổng số phần tử trong mảng
arr.size

# Số chiều của mảng
arr.ndim

# Kiểu dữ liệu của phần tử (int64, float32,...)
arr.dtype

# (3) Thao tác hình dạng
- Thay đổi cấu trúc mảng mà không thay đổi dữ liệu bên trong

In [ ]:
# Thay đổi kích thước mảng
arr.reshape()

# Làm phẳng mảng nhiều chiều thành 1 chiều
arr.flatten()

# Chuyển vị ma trận (dòng thành cột)
arr.transpose()
arr.T

# Nối các mảng lại với nhau
np.concatenate()

# (4) Toàn học & Thống kê (Math & Statistics)
- Numpy thực hiện các phép toán theo cơ chế Broadcasting (tính toán song song trên toàn bộ mảng) thay vì dùng vòng lặp for

In [ ]:
# Các phép toán cơ bản
np.add()
np.subtract()
np.multiply()
np.divide()

# Căn bậc hai
np.sqrt()

# Hàm mũ e
np.exp()

# Log tự nhiên
np.log()

# Tính tổng các phần tử
np.sum()

# Tính giá trị trung bình
np.mean()

# Tính trung vị
np.median()

# Tính độ lệch chuẩn
np.std()

# Vị trí (index) của giá trị nhỏ nhất / lớn nhất
np.argmin()
np.argmax()

# (5) Đại số tuyến tính


In [ ]:
# Tích vô hướng của hai ma trận
np.dot(a, b)
a @ b

# Tìm ma trận nghịch đảo
np.linalg.inv()

# Tìm trị riêng và vector riêng
np.linalg.eig()

# (6) Indexing & Slicing (Truy cập dữ liệu)
- Cách lấy dữ liệu ra khỏi mảng

In [6]:
import numpy as np
'''
Cú pháp: arr[start:stop:step]
    - start: vị trí bắt đầu (lấy cả vị trí này)
    - stop: vị trí kết thúc (không lấy vị trí này)
    - step: mặc định là 1
'''
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
# Index:       0   1   2   3   4   5
# Negative:   -6  -5  -4  -3  -2  -1

# --- INDEXING (Lấy 1 phần tử) ---
print(arr[0])   # 10 (Phần tử đầu tiên)
print(arr[-1])  # 60 (Phần tử cuối cùng)

# --- SLICING (Cắt một đoạn) ---
print(arr[1:4])  # Lấy index 1, 2, 3 -> [20 30 40] (Không lấy index 4)
print(arr[:3])   # Lấy từ đầu đến sát index 3 -> [10 20 30]
print(arr[3:])   # Lấy từ index 3 đến hết -> [40 50 60]

# --- STEP (Bước nhảy) ---
print(arr[::2])  # Lấy từ đầu đến cuối, nhảy 2 bước -> [10 30 50]
print(arr[::-1]) # Đảo ngược mảng -> [60 50 40 30 20 10]

10
60
[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [9]:
arr_2d = np.array([
    [1, 2, 3, 4, 5],       # Hàng 0
    [6, 7, 8, 9, 10],      # Hàng 1
    [11, 12, 13, 14, 15]   # Hàng 2
])

# Lấy một pahnaf tử cụ thể
# Cú pháp: [hàng, cột]
print(arr_2d[1, 2])

# Lấy trọn vẹn một hàng hoặc một cột
# Lấy toàn bộ hàng 1
print(arr_2d[1, :])

# Lấy toàn bộ cột 2
print(arr_2d[:, 2])

# Cắt ma trận con
# Lấy 2 hàng đầu, từ cột 1 đến cột 3
print(arr_2d[:2, 1:4])

8
[ 6  7  8  9 10]
[ 3  8 13]
[[2 3 4]
 [7 8 9]]


In [11]:
# Phân biệt [0, 2] và [[0, 2]]
arr = np.array([
    [10, 11, 12],  # Dòng 0
    [20, 21, 22],  # Dòng 1
    [30, 31, 32]   # Dòng 2
])
# Lấy dòng 0 và dòng 2
print(arr[[0, 2]]) 
# -> [[10, 11, 12],
#     [30, 31, 32]]

[[10 11 12]
 [30 31 32]]


Trường hợp 1: Dùng 1 cặp ngoặc arr[0, 2]
- Đây là Tọa độ (Coordinate).   
    - NumPy hiểu là: "Lấy phần tử ở hàng 0, cột 2".
    - Kết quả: Số vô hướng 12.
Trường hợp 2: Dùng 2 cặp ngoặc lồng nhau arr[[0, 2]]
- Đây là Danh sách các hàng (List of rows).
    - Bạn đang truyền vào một cái List [0, 2] làm chỉ số (index).
    - NumPy hiểu là: "Hãy nhặt cho tôi toàn bộ hàng số 0 và toàn bộ hàng số 2".
    - Kết quả: Một ma trận mới gồm 2 hàng này.

In [19]:
arr = np.array([[
    [1, 5, 3],
    [9, 2, 6],
    [4, 8, 7],
    [0, 3, 2]
]])
sum_of_matrix = np.sum(arr)
max_value = np.max(arr)
min_value = np.min(arr)

arr_random = np.random.random((3, 3))
print(arr_random)


[[0.87282512 0.53369686 0.27246501]
 [0.05870588 0.70547295 0.67155164]
 [0.44187997 0.7157532  0.38042162]]


# (7) Important functions

In [ ]:
# Clip(): Hàm clip cắt giới hạn các giá trị trong một mảng vào một khoảng 
# giá trị nhất định
a = np.array([1, 5, 8, 10, 3, 6])
result = np.clip(a, a_min=3, a_max=8)
print(result)

[3 5 8 8 3 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [33]:
# Concatenate: Nối các mảng lại với nhau theo một trục nhất định
# axis = 0: Từ trên xuống (Chiều hàng)
# axis = 1: Từ trái qua phải (Chiều cột)
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_concate = np.concatenate((arr_1, arr_2), axis = 0)
print(arr_concate)

arr_1 = np.array([
    [1, 2, 3]
])
arr_2 = np.array([
    [4, 5, 6]
])
arr_concate = np.concatenate((arr_1, arr_2), axis = 0)
print(arr_concate)
print(arr_concate.shape)

arr_concate = np.concatenate((arr_1, arr_2), axis = 1)
print(arr_concate)
print(arr_concate.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 4 5 6]]
(1, 6)


In [38]:
# Add more axis: Thêm một trục mới vào mảng, mở rộng số chiều của mảng
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
arr1 = arr[np.newaxis, :]
arr2 = arr[:, np.newaxis]
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [ ]:
# Vectorize(): Chuyển đổi một hàm không phải vector thành một hàm có thể áp
# dụng cho các mảng numpy
def compare(arr1, arr2):
    if arr1 < arr2:
        return 1
    return 0
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 0, 1, 4])
vectorize_compare = np.vectorize(compare)
vectorize_compare(arr1, arr2)


def calculate_circle_area(radius):
    return np.pi * (radius ** 2) 
radius_arr = np.array([1, 2, 3, 4])
calculate_circle_area_vectorize = np.vectorize(calculate_circle_area)
area_arr = calculate_circle_area_vectorize(radius_arr)
print(area_arr)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [43]:
# Where(): Xác định vị trí của các phần tử trong mảng thỏa mãn một điều kiện gì đó
arr = np.array([0, 1, 2, 3, 4])
out = np.where(arr > 3, arr, 0)
print(out)

[0 0 0 0 4]


In [47]:
# Flatten()
arr = np.array([
    [1, 2],
    [3, 4]
])
print(arr)
print(arr.shape)
arr_flatten = arr.flatten()
print(arr_flatten)
print(arr_flatten.shape)

[[1 2]
 [3 4]]
(2, 2)
[1 2 3 4]
(4,)


In [48]:
# reshape(): Thay đổi hình dạng của một mảng mà không làm thay đổi dữ liệu
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(data)
print(data.shape)

data_reshape = data.reshape(3, 2)
print(data_reshape)
print(data_reshape.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
def matrix_multiplication(matrix1, matrix2):
    matrix1_nrows = len(matrix1)
    matrix1_ncols = len(matrix1[0])
    matrix2_nrows = len(matrix2)
    matrix2_ncols = len(matrix2[0])

    result = [[0] * matrix2_ncols for i in range(matrix1_nrows)]

    for i in range(matrix1_nrows):
        for j in range(matrix2_ncols):
            for k in range(matrix2_nrows):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

In [2]:
import numpy as np
X = np.array([
    [1, 2],
    [3, 4]
])
Y = np.array([
    [2, 3],
    [2, 1]
])

print(X.dot(Y))

[[ 6  5]
 [14 13]]
